name: RTEMS 4.10

on: [push, pull_request]

defaults:
  run:
    working-directory: rtems


jobs:
    build:
        name: Build ${{ matrix.arch }}/${{ matrix.bsps }}
        runs-on: ubuntu-latest
        container:
            image: debian:11
        strategy:
            fail-fast: false
            matrix:
                include:
                - arch: i386
                  # may be a commma separated list
                  bsps: pc386
        steps:
            - uses: actions/checkout@v3

            - name: system deps
              run: |
                apt-get -y update
                apt-get -y install bison flex texinfo unzip git python2-dev qemu-system-x86 cmake \
                    cmake build-essential libncurses-dev
                [ -e /usr/bin/python ] || ln -s python2 /usr/bin/python

            - name: check
              run: ../source-builder/sb-check

            - name: build
              run: |
                ../source-builder/sb-set-builder \
                 --log build.log --no-install --bset-tar-file \
                 --prefix "/opt/rtems/4.10" \
                 --with-rtems \
                 --with-rtems-tests=samples \
                 --with-rtemsbsp="${{ matrix.bsps }}" \
                 4.10/rtems-${{ matrix.arch }}.bset

            - name: recompress
              run: |
                 ls -lh tar
                 bzip2 -cd tar/*rtems*kernel*.tar.bz2 | xz -T 0 -9e > ../${{ matrix.bsps }}-rtems4.10.tar.xz
                 ls -lh ../*.xz

            - name: error log
              if: ${{ failure() }}
              run: tail -n 100 build.log

            # upload to possible manual testing
            - name: stash
              uses: actions/upload-artifact@v3
              with:
                  name: bsp-${{ matrix.bsps }}
                  path: ./${{ matrix.bsps }}-rtems4.10.tar.xz
                  retention-days: 1
